// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      label: 'About',
      id: 'README',
    },
    {
      type: 'doc',
      label: 'Charter',
      id: 'docs/CHARTER',
    },
    {
      type: 'doc',
      label: 'Governance',
      id: 'docs/GOVERNANCE',
    },
    {
      type: 'category',
      label: 'Steering Committee',
      items: [
      {
        type: 'doc',
        label: 'Elections',
        id: 'docs/elections/README',
      },
      {
        type: 'doc',
        label: 'Members',
        id: 'docs/STEERING-COMMITTEE',
      },
      ],
    },
    {
      type: 'category',
      label: 'Meetings',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/meetings',
        },
      ],
    },
  ],
}

module.exports = sidebars
